### ISSUE TITLE
Why User Agent is fixed in your code?

### ISSUE THREAD

**Issue by akbansa** [prateekkathal/laravel-simplecurl#3]
You have hard coded User Agent as Mozilla, what does that have to do with the request?
I think it should be one which is really requesting

**Comment by prateekkathal** [comment]
@akbansa Yes, Thanks for the tip. I will make changes to the code ASAP.

**Comment by prateekkathal** [comment]
@akbansa It has been fixed now. Sorry for the delay. 

Let me know if you face anymore issues.
