### ISSUE TITLE
New in Laravel: Class 'SimpleCurl' not found

### ISSUE THREAD

**Issue by sellrock-de** [prateekkathal/laravel-simplecurl#6]
Hello,

i run this in Composer: composer require prateekkathal/laravel-simplecurl 0.* - that installed all fine. Under Vendors i see prateekkathal/ folder.

Then i add under /config/app.php under Providers:
PrateekKathal\SimpleCurl\SimpleCurlServiceProvider::class,

Then i have add under /config/app.php under Aliases:
'SimpleCurl' => PrateekKathal\SimpleCurl\SimpleCurlFacade::class,

Now i am in my Controller and add use SimpleCurl; on the top. I try now a Function from your Curl for testing: 

 $usersArray = SimpleCurl::get('http://localhost/php/messagebird/call/api_voicecall.php')->getResponseAsArray();

Now, if i reload the Site i become the Laravel Error Page - what i do wrong? Can u help me please?
(1/1) FatalThrowableErrorClass 'SimpleCurl' not found
--
in IdentifyController.php (line 110)

Thank you

**Comment by prateekkathal** [comment]
Hi @burhan-kun 

Thanks for the request. I just tried installing this on another directory and did the exact same thing... It works perfectly fine for me so I am not sure.

Can you tell me which Laravel version are you using? Also, did you try doing `composer dump-autoload` or `composer dump-autoload -o`?

Let me know if that works. 

Thanks,
Prateek

**Comment by sellrock-de** [comment]
Hello,

i found what i do wrong: After that all i must clear my config. Then it works. Sorry for the Open Issue. Maybe u can add this Information to your Readme. :-)
