### ISSUE TITLE
SimpleCURL - URL must not be empty

### ISSUE THREAD

**Issue by aditiaprasetio** [prateekkathal/laravel-simplecurl#7]
How can i solved this?

> exception: "Exception"
> file: "..\vendor\prateekkathal\laravel-simplecurl\src\SimpleCurl.php"
> line: 571
> message: "URL must not be empty"

**Comment by prateekkathal** [comment]
@aditiaprasetio You see this exception when you don't pass the URL the curl request has to be made to.
